import { MODELS, GPU_SETUPS, QUANT_LEVELS, getCompatiblePairs, LLAMACPP_REPO, PR_LOOKBACK_DAYS, OUTPUT_DIR, REPORT_FILENAME_PREFIX, modelFitsSetup, freeVramGB } from "./config.js";
import type { ModelEntry, GpuSetup, QuantLevel } from "./config.js";

export function buildSystemPrompt(): string {
  return `You are a technical analyst specializing in llama.cpp, LLM inference, and GPU-accelerated local inference. Your job is to research recently merged PRs in the llama.cpp repository, categorize them, and summarize their impact.

## Your Capabilities
- You can fetch GitHub API endpoints using the webfetch tool to get PR data
- You can write files using the write tool to produce the final report
- You can read files using the read tool to check existing content
- You analyze PR diffs and descriptions to understand what changed and who it affects

## Categorization Rules
When categorizing PRs, use these categories:
- **Backend** — CUDA, Vulkan, Metal, SYCL, ROCm, CPU optimizations, GGML kernel changes
- **Quantization** — New quant types, quantization improvements, IQ changes
- **Model Support** — New architecture support, model-specific fixes, tokenizer updates
- **Performance** — Memory optimizations, speed improvements, batch processing
- **Server/API** — llama-server, HTTP API, OAI-compatible endpoint changes
- **CLI/Tooling** — llama-cli, llama-quantize, llama-perplexity, etc.
- **Bug Fix** — Crash fixes, correctness fixes, edge case handling
- **Documentation** — README, docs, examples
- **Build/CI** — CMake, Makefile, CI pipelines, dependency updates
- **Other** — Anything that doesn't fit above`;
}

export function buildTaskPrompt(): string {
  const compatiblePairs = getCompatiblePairs();
  const today = new Date().toISOString().split("T")[0];
  const outputPath = `${OUTPUT_DIR}/${today}-${REPORT_FILENAME_PREFIX}.md`;

  return `## Task: Generate Llama.cpp Daily News Report

### Step 1: Fetch Recent Merged PRs

Fetch the last ${PR_LOOKBACK_DAYS} days of merged PRs from \`${LLAMACPP_REPO}\` using the GitHub API:
- Endpoint: \`https://api.github.com/repos/${LLAMACPP_REPO}/pulls?state=closed&sort=updated&direction=desc&per_page=50\`
- Use the webfetch tool with appropriate headers (Accept: application/vnd.github+json)
- Filter to only PRs merged in the last ${PR_LOOKBACK_DAYS} days (check merged_at field)
- Focus on PRs with meaningful changes — skip trivial typo fixes and merge-branch PRs

### Step 2: Categorize Each PR

For each PR, determine its primary category from the categorization rules in your system prompt. A PR may touch multiple areas; pick the most impactful one.

### Step 3: Summarize Each PR

For each PR, write a 2-4 sentence summary covering:
- What changed
- Why it matters (who benefits, what improves)
- Any user-facing impact (new flags, changed behavior, new capabilities)

### Step 4: Write the Daily Report

Write the complete report to \`${outputPath}\` using the write tool.

## Report Format

The report must follow this exact markdown structure:

\`\`\`markdown
# Llama.cpp Daily News — ${today}

> Auto-generated by pi-agent-core + DeepSeek | ${LLAMACPP_REPO}
> Model matrix: ${MODELS.length} models × ${GPU_SETUPS.length} GPU setups

---

## 📊 Summary

| Metric | Count |
|--------|-------|
| PRs analyzed | N |
| Backend PRs | N |
| Bug fixes | N |
| Performance PRs | N |
| Model Support | N |
| Server/API | N |
| CLI/Tooling | N |
| Documentation | N |
| Other | N |

---

## 🔍 PR Details

### [Category] — PR #N: Title

**Merged:** YYYY-MM-DD | **Author:** @handle

**Summary:** 2-4 sentence summary of what changed and why it matters.

**Affected areas:** backend1, backend2

---

*Report generated ${new Date().toISOString()} | Next update: tomorrow*
\`\`\`

### Step 5: Update the Run Command Reference

After writing the daily report, you MUST also update the living run command reference page at \`book/src/run-commands.md\`:

1. **Read** the existing file at \`book/src/run-commands.md\` using the read tool
2. **If any of today's PRs introduce new flags, backends, or change recommended parameters:**
   - Update the affected command blocks with new flags or changed values
   - Add a changelog entry at the bottom with today's date and what changed
   - Update the "Last updated" date at the top
3. **If today's PRs don't affect run commands:** still add a "No changes" or "Reviewed — no changes needed" changelog entry so the page shows it was reviewed
4. **Write** the updated file back using the write tool

This page is the canonical reference that persists across daily runs. It should always reflect the best known llama-cli commands based on the latest merged PRs.

## Important Notes
- Use the write tool to save both the daily report and the updated run-commands.md — do NOT just output them in your response
- For PRs you cannot access/fetch, note them in the summary table but skip the details
- If no new PRs were merged in the window, generate a report stating that clearly
- The run-commands.md page uses quant-specific \`<div class="cmd-block" data-quant="Q4_K_M">\` blocks controlled by a JS dropdown. Preserve this structure.
- Model data sourced from Unsloth HuggingFace GGUF repos (\`-hf\` flag syntax)

### Model/GPU compatibility (Q4_K_M baseline):

| Model | ${GPU_SETUPS.map(s => s.name).join(" | ")} |
|-------|${GPU_SETUPS.map(() => "-------").join("|")}|
${MODELS.map(m => `| ${m.name} | ${GPU_SETUPS.map(s => modelFitsSetup(m, "Q4_K_M", s) ? '✅' : `❌ ${s.totalVramGB}GB`).join(" | ")} |`).join("\n")}`;
}
