import { MODELS, GPU_SETUPS, QUANT_LEVELS, getCompatiblePairs, LLAMACPP_REPO, PR_LOOKBACK_DAYS, OUTPUT_DIR, REPORT_FILENAME_PREFIX, modelFitsSetup, freeVramGB } from "./config.js";
import type { ModelEntry, GpuSetup, QuantLevel } from "./config.js";

export function buildSystemPrompt(): string {
  return `You are a technical analyst specializing in llama.cpp, LLM inference, and GPU-accelerated local inference. Your job is to research recently merged PRs in the llama.cpp repository, categorize them, and summarize their impact.

## Your Capabilities
- You can fetch GitHub API endpoints using the webfetch tool to get PR data
- You can write files using the write tool to produce the final report
- You can read files using the read tool to check existing content
- You analyze PR diffs and descriptions to understand what changed and who it affects

## Categorization Rules
When categorizing PRs, use these categories:
- **Backend** — CUDA, Vulkan, Metal, SYCL, ROCm, CPU optimizations, GGML kernel changes
- **Quantization** — New quant types, quantization improvements, IQ changes
- **Model Support** — New architecture support, model-specific fixes, tokenizer updates
- **Performance** — Memory optimizations, speed improvements, batch processing
- **Server/API** — llama-server, HTTP API, OAI-compatible endpoint changes
- **CLI/Tooling** — llama-cli, llama-quantize, llama-perplexity, etc.
- **Bug Fix** — Crash fixes, correctness fixes, edge case handling
- **Documentation** — README, docs, examples
- **Build/CI** — CMake, Makefile, CI pipelines, dependency updates
- **Other** — Anything that doesn't fit above`;
}

export function buildTaskPrompt(): string {
  const compatiblePairs = getCompatiblePairs();
  const today = new Date().toISOString().split("T")[0];
  const outputPath = `${OUTPUT_DIR}/${today}-${REPORT_FILENAME_PREFIX}.md`;

  return `## Task: Generate Llama.cpp Daily News Report

### Step 0: Deduplication — Skip Already-Covered PRs

**CRITICAL:** You MUST prevent duplicate PR coverage across daily reports.

1. **Find previous reports:** List files in \`${OUTPUT_DIR}/\` using bash: \`ls -1r ${OUTPUT_DIR}/*.md 2>/dev/null\`
2. **Identify the most recent report** (the one with the latest date in the filename, e.g. \`2026-06-09-llama-cpp-news.md\`)
3. **Read that report** using the read tool and extract all PR numbers it already covered (look for \`PR #N\` or \`#N\` in PR detail headings)
4. **Set your cutoff date:** Determine the latest \`merged_at\` date of any PR in that report. Only cover PRs merged **after** that date.
5. **If no previous report exists** (first run ever), fall back to a ${PR_LOOKBACK_DAYS}-day lookback window.
6. **Skip covered PRs:** When you encounter a PR you've already seen in a previous report, exclude it — even if it got new comments or updates.

### Step 1: Fetch Recent Merged PRs

Fetch merged PRs from \`${LLAMACPP_REPO}\` using the GitHub API:
- Endpoint: \`https://api.github.com/repos/${LLAMACPP_REPO}/pulls?state=closed&sort=updated&direction=desc&per_page=50\`
- Use the webfetch tool with appropriate headers (Accept: application/vnd.github+json)
- Filter to only PRs merged after your cutoff date (from Step 0) and within the last ${PR_LOOKBACK_DAYS} days at most
- Focus on PRs with meaningful changes — skip trivial typo fixes and merge-branch PRs

### Step 2: Categorize Each PR

For each PR, determine its primary category from the categorization rules in your system prompt. A PR may touch multiple areas; pick the most impactful one.

### Step 3: Summarize Each PR

For each PR, write a 2-4 sentence summary covering:
- What changed
- Why it matters (who benefits, what improves)
- Any user-facing impact (new flags, changed behavior, new capabilities)

### Step 4: Write the Daily Report

Write the complete report to \`${outputPath}\` using the write tool.

## Report Format

The report must follow this exact markdown structure:

\`\`\`markdown
# Llama.cpp Daily News — ${today}

> Auto-generated by pi-agent-core + DeepSeek | ${LLAMACPP_REPO}
> Model matrix: ${MODELS.length} models × ${GPU_SETUPS.length} GPU setups

---

## 📊 Summary

| Metric | Count |
|--------|-------|
| PRs analyzed | N |
| Backend PRs | N |
| Bug fixes | N |
| Performance PRs | N |
| Model Support | N |
| Server/API | N |
| CLI/Tooling | N |
| Documentation | N |
| Other | N |

---

## 🔍 PR Details

### [Category] — PR #N: Title

**Merged:** YYYY-MM-DD | **Author:** @handle

**Summary:** 2-4 sentence summary of what changed and why it matters.

**Affected areas:** backend1, backend2

---

*Report generated ${new Date().toISOString()} | Next update: tomorrow*
\`\`\`

### Step 5: Update the Run Command Reference

After writing the daily report, you MUST also update the living run command reference page at \`book/src/run-commands.md\`:

1. **Read** the existing file at \`book/src/run-commands.md\` using the read tool
2. **Do NOT modify:**
   - The \`<span id="...">\` elements (used by JS for dynamic updates)
   - The \`quant-selector.js\` file
   - The interactive matrix table structure
   - The \`<div class="cmd-block" data-quant="...">\` wrapper structure
3. **Only update inside cmd-block divs:**
   - Update \`-hf\` flags, \`--ctx-size\`, \`--flash-attn\`, \`--tensor-split\` values if new PRs change recommendations
   - Each quant level (Q4_K_M, Q5_K_M, Q6_K) has its own \`cmd-block\` div — update all that are affected
4. **Changelog:** Add entry at the bottom with today's date and what changed. If no changes, add "Reviewed — no changes needed"
5. **Write** the updated file back using the write tool

### Model Data Reference (Unsloth GGUF repos)

Use these exact repos and filenames when writing commands:

| Model | Repo | Q4_K_M file | Q5_K_M file | Q6_K file | Context |
|-------|------|-------------|-------------|-----------|---------|
${MODELS.map(m => `| ${m.name} | \`${m.hfRepo}\` | \`${m.quants.Q4_K_M.filename}\` (${m.quants.Q4_K_M.sizeGB} GB) | \`${m.quants.Q5_K_M.filename}\` (${m.quants.Q5_K_M.sizeGB} GB) | \`${m.quants.Q6_K.filename}\` (${m.quants.Q6_K.sizeGB} GB) | ${m.contextWindow.toLocaleString()} |`).join("\n")}

Commands use \`-hf\` flag syntax: \`-hf REPO:QUANT\` (e.g., \`-hf unsloth/Qwen3.6-35B-A3B-MTP-GGUF:UD-Q4_K_M\`).

### GPU setups (2 GB overhead per GPU for KV cache):
${GPU_SETUPS.map(s => `- ${s.name}: ${s.totalVramGB} GB total (${s.gpuCount}×${s.vramPerGpuGB} GB), ${s.totalVramGB - s.gpuCount * 2} GB usable`).join("\n")}

### VRAM Compatibility Matrix (Q4_K_M baseline):

| Model | ${GPU_SETUPS.map(s => s.name).join(" | ")} |
|-------|${GPU_SETUPS.map(() => "-------").join("|")}|
${MODELS.map(m => `| ${m.name} | ${GPU_SETUPS.map(s => modelFitsSetup(m, "Q4_K_M", s) ? '✅' : `❌`).join(" | ")} |`).join("\n")}

> ⚠️ At Q4_K_M, Qwen 35B (22.66 GB) does NOT fit on 1×3090 (22 GB usable). Only 2×3090 and 2×5060Ti.
> At Q5_K_M (27.09 GB) and Q6_K (30.01 GB), Qwen 35B only fits on 2×3090.`;
}
