import { MODELS, GPU_SETUPS, getCompatiblePairs, LLAMACPP_REPO, PR_LOOKBACK_DAYS, OUTPUT_DIR, REPORT_FILENAME_PREFIX, modelFitsSetup } from "./config.js";
import type { ModelEntry, GpuSetup } from "./config.js";

export function buildSystemPrompt(): string {
  return `You are a technical analyst specializing in llama.cpp, LLM inference, and GPU-accelerated local inference. Your job is to research recently merged PRs in the llama.cpp repository, categorize them, summarize their impact, and generate relevant run-command suggestions.

## Your Capabilities
- You can fetch GitHub API endpoints using the webfetch tool to get PR data
- You can write files using the write tool to produce the final report
- You analyze PR diffs and descriptions to understand what changed and who it affects

## Categorization Rules
When categorizing PRs, use these categories:
- **Backend** — CUDA, Vulkan, Metal, SYCL, ROCm, CPU optimizations, GGML kernel changes
- **Quantization** — New quant types, quantization improvements, IQ changes
- **Model Support** — New architecture support, model-specific fixes, tokenizer updates
- **Performance** — Memory optimizations, speed improvements, batch processing
- **Server/API** — llama-server, HTTP API, OAI-compatible endpoint changes
- **CLI/Tooling** — llama-cli, llama-quantize, llama-perplexity, etc.
- **Bug Fix** — Crash fixes, correctness fixes, edge case handling
- **Documentation** — README, docs, examples
- **Build/CI** — CMake, Makefile, CI pipelines, dependency updates
- **Other** — Anything that doesn't fit above`;
}

export function buildTaskPrompt(): string {
  const compatiblePairs = getCompatiblePairs();

  const modelList = MODELS.map(m =>
    `- **${m.name}** (${m.paramSize} ${m.spec}): ${m.quant} ~${m.estimatedSizeGB}GB, ctx ${m.contextWindow.toLocaleString()}`
  ).join("\n");

  const setupList = GPU_SETUPS.map(s =>
    `- **${s.name}**: ${s.totalVramGB}GB total (${s.gpuCount}×${s.vramPerGpuGB}GB ${s.gpuModel})`
  ).join("\n");

  const pairsList = compatiblePairs.map(p =>
    `| ${p.model.name} | ${p.setup.name} | ${p.setup.totalVramGB}GB VRAM |`
  ).join("\n");

  const today = new Date().toISOString().split("T")[0];
  const outputPath = `${OUTPUT_DIR}/${today}-${REPORT_FILENAME_PREFIX}.md`;

  return `## Task: Generate Llama.cpp Daily News Report

### Step 1: Fetch Recent Merged PRs

Fetch the last ${PR_LOOKBACK_DAYS} days of merged PRs from \`${LLAMACPP_REPO}\` using the GitHub API:
- Endpoint: \`https://api.github.com/repos/${LLAMACPP_REPO}/pulls?state=closed&sort=updated&direction=desc&per_page=50\`
- Use the webfetch tool with appropriate headers (Accept: application/vnd.github+json)
- Filter to only PRs merged in the last ${PR_LOOKBACK_DAYS} days (check merged_at field)
- Focus on PRs with meaningful changes — skip trivial typo fixes and merge-branch PRs

### Step 2: Categorize Each PR

For each PR, determine its primary category from the categorization rules in your system prompt. A PR may touch multiple areas; pick the most impactful one.

### Step 3: Summarize Each PR

For each PR, write a 2-4 sentence summary covering:
- What changed
- Why it matters (who benefits, what improves)
- Any user-facing impact (new flags, changed behavior, new capabilities)

### Step 4: Generate Run Command Suggestions

For PRs that affect inference (Backend, Performance, Model Support, Quantization), generate run command suggestions. For EACH compatible model×GPU pair:

${compatiblePairs.length > 0 ? `The following ${compatiblePairs.length} model×GPU pairs are VRAM-compatible:\n\n| Model | GPU Setup | Total VRAM |\n|-------|-----------|--------|\n${pairsList}` : 'No compatible pairs found.'}

For each relevant PR, generate at least one concrete, runnable llama.cpp CLI command per compatible pair. Commands must include:
- Exact model GGUF filename (from HuggingFace repos)
- \`--model\` path
- \`--n-gpu-layers\` (offload all layers: 999 or specific count)
- \`--ctx-size\` (use model's native context window or a practical value)
- \`--flash-attn\` (enable when relevant, especially for large contexts)
- \`--split-mode layer\` (for multi-GPU setups)
- \`--tensor-split\` with VRAM-proportional values (for multi-GPU setups)
- \`--threads\` (CPU thread count recommendation)
- \`--no-mmap\` (when relevant for Windows or low-RAM systems)
- \`--temp\`, \`--repeat-penalty\`, \`--top-p\`, \`--top-k\` (reasonable defaults)
- Any new flags introduced by the PR

### Step 5: Write the Report

Write the complete report to \`${outputPath}\` using the write tool.

## Report Format

The report must follow this exact markdown structure:

\`\`\`markdown
# Llama.cpp Daily News — ${today}

> Auto-generated by pi-agent-core + DeepSeek | ${LLAMACPP_REPO}
> Model matrix: ${MODELS.length} models × ${GPU_SETUPS.length} GPU setups
> Compatible pairs (VRAM-filtered): ${compatiblePairs.length}

---

## 📊 Summary

| Metric | Count |
|--------|-------|
| PRs analyzed | N |
| Backend PRs | N |
| Bug fixes | N |
| Performance PRs | N |
| New features | N |
| PRs with command suggestions | N |

---

## 🔍 PR Details

### [Category] — PR #N: Title

**Merged:** YYYY-MM-DD | **Author:** @handle

**Summary:** 2-4 sentence summary of what changed and why it matters.

**Affected areas:** backend1, backend2

---

## 🖥️ Run Command Suggestions

### Model: [Model Name] | Setup: [GPU Setup]

> **PR #N: Title** — [one-line reason this PR affects these commands]

\`\`\`bash
# Download the model (if needed)
huggingface-cli download [hfRepo] [ggufPattern].gguf --local-dir ./models

# Run with llama.cpp
./llama-cli \\
  --model ./models/[ggufPattern].gguf \\
  --n-gpu-layers 999 \\
  --ctx-size [value] \\
  --flash-attn \\
  --split-mode layer \\
  --tensor-split [values] \\
  --threads [count] \\
  --temp 0.7 \\
  --repeat-penalty 1.1 \\
  --top-p 0.9 \\
  --top-k 40 \\
  -p "Your prompt here"
\`\`\`

---

## 📋 Command Quick-Reference Matrix

| Model | ${GPU_SETUPS.map(s => s.name).join(" | ")} |
|-------|${GPU_SETUPS.map(() => "-------").join("|")}|
${MODELS.map(m => `| ${m.name} | ${GPU_SETUPS.map(s => modelFitsSetup(m, s) ? '✅' : `❌ ${s.totalVramGB}GB`).join(" | ")} |`).join("\n")}

---

*Report generated ${new Date().toISOString()} | Next update: tomorrow*
\`\`\`

## Important Notes
- Use the write tool to save the report — do NOT just output it in your response
- For PRs you cannot access/fetch, note them in the summary table but skip the details
- If no new PRs were merged in the window, generate a report stating that clearly
- When suggesting commands, ensure flags are compatible with the model architecture (e.g., Qwen models need --flash-attn for long contexts)`;
}
